version: '3'

services:
  app:
    container_name: app
    build: 
      context: ./php
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/var/www/html
    networks:
      - dvwa
  
  web:
    container_name: web
    image: nginx:1.17
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx_local_template.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8086:80"
    networks:
      - dvwa
  
  db:
    container_name: db
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "dvwa"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "password"
    volumes: 
      - ./mysqldata:/var/lib/mysql
    networks:
      - dvwa
    
    
volumes:
    mysqldata:
networks:
  dvwa:
    driver: bridge

